apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  labels:
    app: webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: nginxdemos/hello:latest
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: webapp-config
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        
        # --- LIVENESS PROBE MEJORADO ---
        livenessProbe:
          httpGet:
            path: /healthz/live
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 2       # Tiempo máximo para la respuesta
          failureThreshold: 5     # Número de fallos antes de reiniciar
          
        # --- READINESS PROBE MEJORADO ---
        readinessProbe:
          httpGet:
            path: /healthz/ready
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 2       # Tiempo máximo para la respuesta
